name: Hello Actions

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      your_name:
        description: "Satan"
        required: true
        default: "Mehran"
      message:
        description: "I changed you"
        required: true
        default: "Learning GitHub Actions!"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build step (demo)
        run: |
          echo "Building..."
          mkdir -p out
          echo "Built by $GITHUB_ACTOR on $(date)" > out/build.txt
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: out/build.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: out
      - name: Test step (demo)
        run: |
          echo "Testing..."
          cat out/build.txt
          echo "âœ… Tests passed"


