name: Hello Actions

on:
  push:
  workflow_dispatch:
    inputs:
      your_name:
        description: "Satan"
        required: true
        default: "Mehran"
      message:
        description: "I changed you"
        required: true
        default: "Learning GitHub Actions!"


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (download code)
        uses: actions/checkout@v4
    
      - name: Print inputs
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Name: ${{ inputs.your_name || github.actor }}"
          echo "Message: ${{ inputs.message || 'Triggered by push (no manual inputs)' }}"

    
      - name: Print README title line
        run: head -n 3 README.md

