name: Hello Actions

on:
  push:
  workflow_dispatch:
    inputs:
      your_name:
        description: "Your name"
        required: true
        default: "Mehran"
      message:
        description: "Message to print"
        required: true
        default: "Learning GitHub Actions!"


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (download code)
        uses: actions/checkout@v4
    
      - name: Print inputs
        run: |
          echo "Name: ${{ inputs.your_name }}"
          echo "Message: ${{ inputs.message }}"
    
      - name: Print README title line
        run: head -n 3 README.md

